Events
Ashah15/Private-events pull request #1
Opened 2019-12-31 08:49 UTC by Ashah15

2019-12-31 09:56 UTC, maelfosso requested changes
# Changes required

Hello @Ashah15 @MarvellousUbani 

THank you for that project. I really loved the design :smile_cat: 
However, there are some features not implemented
1. According to that [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png), the user's show page displays events the user has created and events that the user is attending to separated in past and upcoming
**Here is the list of created event**. You will notice some created by **_Alice_**
![Screenshot from 2019-12-31 10-36-50](https://user-images.githubusercontent.com/8848104/71617111-cdce1280-2bb9-11ea-83d4-77b0a830dbb1.png)
But if I **open the user (alice) show page**, you won't see anything
![Screenshot from 2019-12-31 10-37-14](https://user-images.githubusercontent.com/8848104/71617128-f524df80-2bb9-11ea-89c6-459ac6d7b689.png)

2. You should write integrations tests. There are none tests in your code.

3. Read the comments below.


Kindly make the changes and submit a new code review request.
Thank you.

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2019-12-31 09:56 UTC, maelfosso commented on private-events/app/models/user.rb
> +    digest = send("#{attribute}_digest")
Why that line please?

2019-12-31 09:56 UTC, maelfosso commented on private-events/app/controllers/events_controller.rb
> +    	@user = current_user
Why do you need that?

2019-12-31 09:56 UTC, maelfosso commented on private-events/app/controllers/users_controller.rb
> +		@user = current_user
Why that line?

2019-12-31 09:56 UTC, maelfosso commented on private-events/app/controllers/users_controller.rb
> +		@past_events = Event.past.joins(:attendees).where(attendees: { name: current_user.username })
Please, I suggest you use `@current_user.attendees.upcoming`.

2019-12-31 09:56 UTC, maelfosso commented on private-events/app/controllers/users_controller.rb
> +    end
That method is repeated. I saw it in **EventController** too. 
Please, could you move it in **ApplicationController**

2020-01-02 21:40 UTC, Redvanisation requested changes
# Changes required  ♻️ 

### Hello team  🌟

**Nice work so far but the following issues need to be fixed ⬇️** 

- The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations)).

- You need to write integration tests for all the futures.

- Implement the changes from the previous code review.

- Set up Stickler to lint your code, find out more on how to do that in [here](https://github.com/microverseinc/linters-config).

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2020-01-07 09:45 UTC, maelfosso requested changes
# :wave: :wave:  Hello I can see you did some Improvements based on the review, lets take a look eye_speech_bubble shall we.

- According to that [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png) to see the detail of the event, the user should be logged in, please fix it.

- Also you forgot to write integration tests for Event. And about testing, they should write using Rspec. Please, check that in that [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/unit_tests_requirement.png)
So, please rewrite them all using RSpec.

- There is that error when trying to see the event details from the home page when the user is not connected
![Screenshot from 2020-01-07 10-24-01](https://user-images.githubusercontent.com/8848104/71885469-b99a9000-313a-11ea-94e3-976f69e05648.png)

Kindly make the changes and submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

2020-01-07 09:45 UTC, maelfosso commented on private-events/app/controllers/events_controller.rb
> +	before_action :logged_in_user, only: [:new, :create]
I think you should add show here, otherwise there will be an error.

2020-01-08 19:47 UTC, samgaco approved these changes
Everything corrected accordingly, you can move on :+1: 

------------------

* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2020-01-08 19:47 UTC, samgaco commented on spec/features/create_event_spec.rb
> +	  end
:+1:

2020-01-08 19:51 UTC, merged